engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  reek:
    enabled: true
  rubocop:
    enabled: true

exclude_paths:
- spec/**/*

ratings:
   paths:
   - "**.rb"
