inherit_from: .rubocop_todo.yml

# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ExtraSpacing:
  AllowForAlignment: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200

# Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Enabled: false
