sudo: false
language: ruby

cache:
  bundler: true

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

after_script:
  - bundle exec codeclimate-test-reporter
