sudo: false
language: ruby

cache:
  bundler: true

rvm:
  - 2.5.3
  - 2.3.1
  - 2.2.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

after_script:
  - bundle exec codeclimate-test-reporter
